using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Versioning;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Resources;
using Windows.ApplicationModel;

namespace EventLook.Model;
internal static class BuildInfo
{
    /// <summary>
    /// Simplified package type to be consumed by About menu.
    /// </summary>
    public enum PackageType
    {
        NotPackaged,    // Standalone build such as artifact in GitHub.
        DevPackage,     // Private build of EventLookPackage.
        Store           // Formal release.
    }
    
    /// <summary>
    /// Gets build date from a resource file embedded in the app. 
    /// The resource file is to be generated by pre-build command.
    /// </summary>
    /// <returns></returns>
    public static DateTime GetBuildDate()
    {
        StreamResourceInfo info = Application.GetResourceStream(new Uri("/BuildDate.txt", UriKind.Relative));
        using var sr = new StreamReader(info.Stream);
        string dateString = sr.ReadLine();
        if (DateTime.TryParse(dateString, out DateTime buildDate))
            return buildDate;
        else
            return DateTime.MinValue;
    }

    /// <summary>
    /// Determines the simplified package type of this application.
    /// If the environment is very old (like Win8 or very early version of Win10), treats as not packaged.
    /// </summary>
    /// <returns></returns>
    public static PackageType GetPackageType()
    {
        if (!OperatingSystem.IsWindowsVersionAtLeast(10, 0, 14393))
        {
            return PackageType.NotPackaged;
        }
        try
        {
            Package package = Package.Current;
            return package.SignatureKind switch
            {
                PackageSignatureKind.None or PackageSignatureKind.Developer or PackageSignatureKind.Enterprise => PackageType.DevPackage,
                PackageSignatureKind.Store or PackageSignatureKind.System => PackageType.Store,
                _ => PackageType.NotPackaged,
            };
        }
        catch (Exception)
        {
            return PackageType.NotPackaged;
        }
    }
}
